sudo: false

language: go

go:
  - 1.8.x
  - tip

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - godep save

script:
  - go test -v ./...

notifications:
  email: false
